apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:3.2.0
          ports:
            - containerPort: 9200
            - containerPort: 9600
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "PasswordMoltoForte123!"
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: bootstrap.memory_lock
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          ulimits:
            # alcuni runtime ignorano, ma lo lasciamo per completezza
          volumeMounts:
            - name: os-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: os-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: wso2
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
        - name: dashboards
          image: opensearchproject/opensearch-dashboards:3.2.0
          env:
            - name: OPENSEARCH_HOSTS
              value: '["http://opensearch:9200"]'
            - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
              value: "true"
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: wso2
spec:
  selector:
    app: opensearch-dashboards
  ports:
    - name: http
      port: 5601
      targetPort: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-dashboards
  namespace: wso2
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - analytics.wso2.com
      secretName: am-wso2-com-tls
  rules:
    - host: analytics.wso2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-dashboards
                port:
                  number: 5601
